# Generated by Django 3.2.3 on 2021-06-05 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_user_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendships',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='friendships',
            name='status',
        ),
    ]
